#!/usr/bin/env bash

###############################################################################
#
# Kali Recovery Toolkit
#
###############################################################################

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Framework Initialization
#

source "${ROOT_DIR}/core/initialize.sh"

#
# CLI Dispatcher
#

source "${ROOT_DIR}/core/cli/dispatch.sh"

#
# Start Framework
#

initialize_framework

#
# Execute Command
#

dispatch_command "$1"
