###############################################################################
#
# GRUB Module Configuration
#
###############################################################################

MODULE_NAME="GRUB Inspector"

MODULE_VERSION="1.0"

MODULE_AUTHOR="Alfredo San"

MODULE_DESCRIPTION="Inspect the GRUB bootloader configuration"

ENABLED=true

