#!/usr/bin/env bash

###############################################################################
#
# Kali Recovery Toolkit
# Module Generator
#
###############################################################################

set -e

MODULE_NAME="$1"

if [[ -z "$MODULE_NAME" ]]; then
    echo
    echo "Usage:"
    echo
    echo "    ./tools/create_module.sh <module_name>"
    echo
    exit 1
fi

MODULE_DIR="modules/${MODULE_NAME}"

if [[ -d "$MODULE_DIR" ]]; then
    echo
    echo "[ERROR] Module already exists."
    exit 1
fi

echo
echo "Creating module: ${MODULE_NAME}"
echo

mkdir -p "${MODULE_DIR}"
mkdir -p "${MODULE_DIR}/tests"

###############################################################################
# module.conf
###############################################################################

cat > "${MODULE_DIR}/module.conf" <<EOF
###############################################################################
#
# ${MODULE_NAME^} Module Configuration
#
###############################################################################

MODULE_NAME="${MODULE_NAME^} Inspector"

MODULE_VERSION="1.0"

MODULE_AUTHOR="Alfredo San"

MODULE_DESCRIPTION="${MODULE_NAME^} Inspector"

ENABLED=true
EOF

###############################################################################
# README
###############################################################################

cat > "${MODULE_DIR}/README.md" <<EOF
# ${MODULE_NAME^} Inspector

## Description

Module generated by KRT Module Generator.

## Command

\`\`\`bash
./krt --${MODULE_NAME}
\`\`\`
EOF

###############################################################################
# module.sh
###############################################################################

cat > "${MODULE_DIR}/module.sh" <<EOF
#!/usr/bin/env bash

###############################################################################
#
# ${MODULE_NAME^} Inspector
#
###############################################################################

source "\${ROOT_DIR}/services/collector/collector.sh"
source "\${ROOT_DIR}/services/report/report.sh"
source "\${ROOT_DIR}/services/health/health.sh"

run_${MODULE_NAME}() {

    log_info "Initializing ${MODULE_NAME^} Inspector..."

    echo
    echo "=============================================================="
    echo "                  ${MODULE_NAME^} Inspector"
    echo "=============================================================="
    echo

    log_success "${MODULE_NAME^} Inspector completed."

}
EOF

chmod +x "${MODULE_DIR}/module.sh"

echo
echo "Module created successfully."
echo
echo "Location:"
echo
echo "    ${MODULE_DIR}"
echo
echo "Files:"
echo
echo "    module.sh"
echo "    module.conf"
echo "    README.md"
echo "    tests/"
echo
