#!/usr/bin/env bash

###############################################################################
#
# Kali Recovery Toolkit
# Module Generator
#
###############################################################################

set -e

MODULE_NAME="$1"

###############################################################################
# Validate module name
###############################################################################

if [[ -z "$MODULE_NAME" ]]; then
    echo
    echo "Usage:"
    echo
    echo "    ./tools/create_module.sh <module_name>"
    echo
    exit 1
fi

if [[ "$MODULE_NAME" == -* ]]; then
    echo
    echo "[ERROR] Invalid module name: $MODULE_NAME"
    echo "Module names cannot start with '-'."
    exit 1
fi

if [[ ! "$MODULE_NAME" =~ ^[a-z][a-z0-9_-]*$ ]]; then
    echo
    echo "[ERROR] Invalid module name."
    echo "Allowed characters:"
    echo "  - lowercase letters"
    echo "  - numbers"
    echo "  - '-'"
    echo "  - '_'"
    exit 1
fi

MODULE_DIR="modules/${MODULE_NAME}"

if [[ -d "$MODULE_DIR" ]]; then
    echo
    echo "[ERROR] Module already exists."
    exit 1
fi

echo
echo "Creating module: ${MODULE_NAME}"
echo

mkdir -p "${MODULE_DIR}"
mkdir -p "${MODULE_DIR}/tests"

###############################################################################
# module.conf
###############################################################################

cat > "${MODULE_DIR}/module.conf" <<EOF
###############################################################################
#
# ${MODULE_NAME^} Module Configuration
#
###############################################################################

MODULE_NAME="${MODULE_NAME^} Inspector"

MODULE_VERSION="1.0"

MODULE_AUTHOR="Alfredo San"

MODULE_DESCRIPTION="${MODULE_NAME^} Inspector"

ENABLED=true
EOF

###############################################################################
# README
###############################################################################

cat > "${MODULE_DIR}/README.md" <<EOF
# ${MODULE_NAME^} Inspector

## Description

This module inspects the ${MODULE_NAME^} subsystem.

## Responsibilities

- Collect system information
- Evaluate system health
- Render inspection output
- Generate reports

## Command

\`\`\`bash
./krt --${MODULE_NAME}
\`\`\`

## Status

Module template generated by the KRT Module Generator.
EOF

###############################################################################
# module.sh
###############################################################################

cat > "${MODULE_DIR}/module.sh" <<EOF
#!/usr/bin/env bash

###############################################################################
#
# ${MODULE_NAME^} Inspector
#
###############################################################################

source "\${ROOT_DIR}/services/logger/logger.sh"
source "\${ROOT_DIR}/services/collector/collector.sh"
source "\${ROOT_DIR}/services/health/health.sh"
source "\${ROOT_DIR}/services/inspector/inspector.sh"
source "\${ROOT_DIR}/services/report/report.sh"

###############################################################################
# ${MODULE_NAME^} Inspector
###############################################################################

run_${MODULE_NAME}() {

    log_info "Initializing ${MODULE_NAME^} Inspector..."

    echo
    echo "=============================================================="
    echo "                  ${MODULE_NAME^} Inspector"
    echo "=============================================================="
    echo

    ###########################################################################
    # Collect information
    ###########################################################################

    # TODO:
    # collect_${MODULE_NAME}_information

    ###########################################################################
    # Evaluate health
    ###########################################################################

    # TODO:
    # health_${MODULE_NAME}

    ###########################################################################
    # Render inspector output
    ###########################################################################

    # TODO:
    # inspector_${MODULE_NAME}

    ###########################################################################
    # Generate report
    ###########################################################################

    # TODO:
    # report_${MODULE_NAME}

    log_success "${MODULE_NAME^} Inspector completed."

}
EOF

chmod +x "${MODULE_DIR}/module.sh"

echo
echo "=============================================================="
echo " Module created successfully"
echo "=============================================================="
echo
echo "Location:"
echo "    ${MODULE_DIR}"
echo
echo "Files:"
echo "    module.sh"
echo "    module.conf"
echo "    README.md"
echo "    tests/"
echo
echo "Next steps:"
echo
echo "  1. Implement collectors"
echo "  2. Implement health checks"
echo "  3. Implement inspector output"
echo "  4. Implement report generation"
echo "  5. Register the module in the dispatcher"
echo
