###############################################################################
# KRT Backup Module
###############################################################################

MODULE_NAME="Backup Module"

MODULE_ID="backup"

MODULE_VERSION="1.0.0"

MODULE_AUTHOR="Alfredo San"

MODULE_DESCRIPTION="Creates recovery backups before executing critical operations."

ENTRYPOINT="module.sh"

ENABLED="true"
